spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:h2:tcp://localhost/~/board_jh
    username: kjh
    password: 1234
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        default-page-size: 20  #페이징 할 때 기본값, 20개씩 조회

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #배치 사이즈 (Collection 조회 최적화)

  profiles:
    include: jwt

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace